sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_version.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_a_and_e.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_age_group_names.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_geographies.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_health_study_themes.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_icd10.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_icd9.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_icd_o_3.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_opcs4.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_outcomes.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_reference_tables.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_projects.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_num_denom.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_parameters.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_error_messages.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_user_projects.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_tables_and_views.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_age_groups.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_geolevels.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_covariates.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_outcome_groups.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_predefined_groups.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_tables.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_table_outcomes.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_studies.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_study_shares.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_comparison_areas.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_investigations.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_contextual_stats.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_fdw_tables.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_study_sql_log.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_study_sql.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_inv_covariates.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_inv_conditions.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_columns.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\rif40_triggers.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\tables\t_rif40_study_areas.sql
