/*
Need some test people - $(USERNAME) is the user environment username (admin in my case)

THIS SCRIPT MUST BE RUN AS ADMINSITRATOR
*/

BEGIN
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'$(USERNAME)')
    BEGIN
		CREATE LOGIN $(USERNAME) WITH PASSWORD='$(USERNAME)';
		CREATE USER [$(USERNAME)] FOR LOGIN [$(USERNAME)] WITH DEFAULT_SCHEMA=[dbo];
		ALTER SERVER ROLE [rif_manager] ADD MEMBER [$(USERNAME)];
		ALTER SERVER ROLE [rif_user] ADD MEMBER [$(USERNAME)];		
	END;
	
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'$(USERNAME)')
	BEGIN
		EXEC('CREATE SCHEMA [$(USERNAME)] AUTHORIZATION [$(USERNAME)]');
		ALTER USER [$(USERNAME)] WITH DEFAULT_SCHEMA=[$(USERNAME)];
	END;

SELECT name, type_desc FROM sys.database_principals WHERE name = N'$(USERNAME)';
SELECT * FROM sys.schemas WHERE name = N'$(USERNAME)';

END;
GO
