sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\rif40_version_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\t_rif40_user_projects_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\rif40_study_shares_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\rif40_covariates_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\rif40_tables_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\rif40_table_outcomes_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\rif40_error_messages_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\rif40_geographies_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\t_rif40_comparison_areas_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\t_rif40_contextual_stats_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\t_rif40_geolevels_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\t_rif40_inv_conditions.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\t_rif40_inv_covariates.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\t_rif40_investigations.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\t_rif40_results.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\t_rif40_study_areas_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\t_rif40_study_sql_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\t_rif40_study_sql_log_trigger.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\table_triggers\t_rif40_studies.sql
