sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_comparison_areas.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_contextual_stats.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_fdw_tables.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_geolevels.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_investigations.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_inv_conditions.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_inv_covariates.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_parameters.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_projects.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_studies.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_study_sql.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_study_sql_log.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_user_projects.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_user_version.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_results.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_num_denom.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_numerator_outcome_columns.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_num_denom_errors.sql
sqlcmd -d sahsuland_dev -i ..\sahsuland_dev\rif40\views\rif40_study_areas.sql
