\echo * Script: ../sahsuv3_v4/create_v4_0_postgres_comments.sql autogenerated using: $Id$ by: RIF40 on: 03-MAR-2014
\echo * Comment Postgres tables/views
-- ************************************************************************
-- *
-- * DO NOT EDIT THIS SCRIPT OR MODIFY THE RIF SCHEMA - USE ALTER SCRIPTS
-- *
-- ************************************************************************
--
-- ************************************************************************
--
-- GIT Header
--
-- $Format:Git ID: (%h) %ci$
-- $Id$
-- Version hash: $Format:%H$
--
-- Description:
--
-- Rapid Enquiry Facility (RIF) - Comment Postgres tables/views
--
-- Copyright:
--
-- The Rapid Inquiry Facility (RIF) is an automated tool devised by SAHSU 
-- that rapidly addresses epidemiological and public health questions using 
-- routinely collected health and population data and generates standardised 
-- rates and relative risks for any given health outcome, for specified age 
-- and year ranges, for any given geographical area.
--
-- Copyright 2014 Imperial College London, developed by the Small Area
-- Health Statistics Unit. The work of the Small Area Health Statistics Unit 
-- is funded by the Public Health England as part of the MRC-PHE Centre for 
-- Environment and Health. Funding for this project has also been received 
-- from the Centers for Disease Control and Prevention.  
--
-- This file is part of the Rapid Inquiry Facility (RIF) project.
-- RIF is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Lesser General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- RIF is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU Lesser General Public License for more details.
--
-- You should have received a copy of the GNU Lesser General Public License
-- along with RIF. If not, see <http://www.gnu.org/licenses/>; or write 
-- to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, 
-- Boston, MA 02110-1301 USA
--
-- Author:
--
-- Peter Hambly, SAHSU
--
\set ECHO all
\set ON_ERROR_STOP ON
\timing

--
-- Check user is rif40
--
DO LANGUAGE plpgsql $$
BEGIN
	IF user = 'rif40' THEN
		RAISE INFO 'User check: %', user;	
	ELSE
		RAISE EXCEPTION 'C20900: User check failed: % is not rif40', user;	
	END IF;
END;
$$;

--
-- Check database is sahsuland_dev or sahsuland_empty
--
DO LANGUAGE plpgsql $$
BEGIN
	IF current_database() = 'sahsuland_dev' THEN
		RAISE INFO 'Database check: %', current_database();	
	ELSIF current_database() = 'sahsuland_empty' THEN
		RAISE INFO 'Database check: %', current_database();	
	ELSE
		RAISE EXCEPTION 'C20901: Database check failed: % is not sahsuland_dev or sahsuland_empty', current_database();	
	END IF;
END;
$$;

COMMENT ON TABLE "rif40_a_and_e" IS 'A&E clinical diagnosis (3 char)';
COMMENT ON TABLE "rif40_age_group_names" IS 'RIF Age group names';
COMMENT ON TABLE "rif40_age_groups" IS 'RIF age groups';
COMMENT ON TABLE "rif40_covariates" IS 'RIF multiple covariates';
COMMENT ON TABLE "rif40_dual" IS 'RIF40 version of dual table (for remote execution on Postgres)';
COMMENT ON TABLE "rif40_error_messages" IS 'RIF error messages resulting from schema violations';
COMMENT ON TABLE "rif40_geographies" IS 'Pre-defined hierarchial geographies. Usually based on Census geography. Beware of the foreign key from RIF40_GEOGRAPHIES.DEFAULTCOMPAREA to RIF40_GEOLEVELS. When inserting a new geography do NOT set DEFAULTCOMPAREA, update it after adding geolevels to T_RIF40_GEOLEVELS';
COMMENT ON TABLE "rif40_health_study_themes" IS 'RIF health study themes';
COMMENT ON TABLE "rif40_icd10" IS 'ICD10 code (SAHSU historic version, needs to be updated)';
COMMENT ON TABLE "rif40_icd9" IS 'ICD9 code (SAHSU historic version, needs to be updated)';
COMMENT ON TABLE "rif40_icd_o_3" IS 'International Classification of Disease for Oncology';
COMMENT ON TABLE "rif40_opcs4" IS 'Office of Population Censuses and Surveys [OPCS] Classification of Interventions and Procedures';
COMMENT ON TABLE "rif40_outcome_groups" IS 'Collection of Health outcomes into logical groups. E.g. Single variable ICD9 and 10';
COMMENT ON TABLE "rif40_outcomes" IS 'Health Outcomes. This table give the locations of the various Health Outcomes lookup tables, e.g RIF40_ICD10. Outcomes typically supported are ICD 9, 10, OPCS4 operation codes, ICD-0 Histology';
COMMENT ON TABLE "rif40_predefined_groups" IS 'Predefined Health Outcomes';
COMMENT ON TABLE "rif40_reference_tables" IS 'List of references tables without constraints';
COMMENT ON TABLE "rif40_study_shares" IS 'Users granted access by a RIF_MANAGER to study data';
COMMENT ON TABLE "rif40_table_outcomes" IS 'Intersection of health outcomes in logical groups and Health tables. Mutliple groups supported per table';
COMMENT ON TABLE "rif40_tables" IS 'RIF numerator and denominator tables';
COMMENT ON TABLE "rif40_version" IS 'RIF version';
/*
COMMENT ON TABLE gis.sahsuland_geography IS 'SAHSU example database - geography';
COMMENT ON TABLE gis.sahsuland_level1 IS 'level1';
COMMENT ON TABLE gis.sahsuland_level2 IS 'level2';
COMMENT ON TABLE gis.sahsuland_level3 IS 'level3';
COMMENT ON TABLE gis.sahsuland_level4 IS 'level4';
*/
COMMENT ON TABLE "t_rif40_comparison_areas" IS 'Links comparison areas and bands for a given study.';
COMMENT ON TABLE "t_rif40_contextual_stats" IS 'Contextual stats for results map. Also includes values used in internal calculations.';
COMMENT ON TABLE "t_rif40_fdw_tables" IS 'RIF numerator tables which are Foreign data wrappers in Postgres';
COMMENT ON TABLE "t_rif40_geolevels" IS 'Geolevels: hierarchy of level with a geography. Use this table for INSERT/UPDATE/DELETE; use RIF40_GEOLEVELS for SELECT. In RIF40_GEOLEVELS if the user has the RIF_STUDENT role the geolevels are restricted to LADUA/DISTRICT level resolution or lower.';
COMMENT ON TABLE "t_rif40_inv_conditions" IS 'Lines of SQL conditions pertinent to an investigation.';
COMMENT ON TABLE "t_rif40_inv_covariates" IS 'Details of each covariate used by an investigation in a study';
COMMENT ON TABLE "t_rif40_investigations" IS 'Details of each investigation in a study';
COMMENT ON TABLE "t_rif40_num_denom" IS 'Private copy of extra numerator and denominator pairs not added automatically.';
COMMENT ON TABLE "t_rif40_parameters" IS 'RIF40 parameters. Use this table for INSERT/UPDATE/DELETE; use RIF40_PARAMETERS for SELECT. User needs RIF_NO_SUPPRESSION granted as a role to see unsuppressed results';
COMMENT ON TABLE "t_rif40_projects" IS 'RIF projects';
COMMENT ON TABLE "t_rif40_results" IS 'RIF Results Table';
COMMENT ON TABLE "t_rif40_studies" IS 'RIF studies';
COMMENT ON TABLE "t_rif40_study_areas" IS 'Links study areas and bands for a given study.';
COMMENT ON TABLE "t_rif40_study_sql" IS 'SQL created for study execution.';
COMMENT ON TABLE "t_rif40_study_sql_log" IS 'Log of SQL executed for study.';
COMMENT ON TABLE "t_rif40_user_projects" IS 'RIF project users';

COMMENT ON COLUMN "rif40_a_and_e"."a_and_e_3char" IS 'Clinical diagnosis';
COMMENT ON COLUMN "rif40_a_and_e"."text_3char" IS 'Clinical diagnosis chapter textual description';
COMMENT ON COLUMN "rif40_age_group_names"."age_group_id" IS 'AGE_GROUP_ID';
COMMENT ON COLUMN "rif40_age_group_names"."age_group_name" IS 'Age Group Name';
COMMENT ON COLUMN "rif40_age_groups"."age_group_id" IS 'AGE_GROUP_ID';
COMMENT ON COLUMN "rif40_age_groups"."fieldname" IS 'Fieldname';
COMMENT ON COLUMN "rif40_age_groups"."high_age" IS 'High age';
COMMENT ON COLUMN "rif40_age_groups"."low_age" IS 'Low age';
COMMENT ON COLUMN "rif40_age_groups"."offset" IS 'Offset';
COMMENT ON COLUMN rif40_covariates.covariate_name IS 'Covariate name. This will be a column name in RIF40_GEOLEVELS.COVARIATE_TABLE';
COMMENT ON COLUMN rif40_covariates.geography IS 'Geography (e.g EW2001)';
COMMENT ON COLUMN rif40_covariates.geolevel_name IS 'Name of geolevel. This will be a column name in the numerator/denominator tables';
COMMENT ON COLUMN rif40_covariates.max IS 'Maximum value';
COMMENT ON COLUMN rif40_covariates.min IS 'Minimum value';
COMMENT ON COLUMN rif40_covariates.type IS 'TYPE of covariate (1=integer score/2=continuous variable). Min &lt; max  max/min precison is appropriate to type. Continuous variables are not currently supported. Integer scores can be a binary variable 0/1 or an NTILE e.g. 1..5 for a quintile.';
COMMENT ON COLUMN "rif40_dual"."dummy" IS 'Dummy column';
COMMENT ON COLUMN "rif40_error_messages"."action" IS 'Action to resolve error';
COMMENT ON COLUMN "rif40_error_messages"."cause" IS 'Cause of error';
COMMENT ON COLUMN "rif40_error_messages"."error_code" IS 'Error code';
COMMENT ON COLUMN "rif40_error_messages"."message" IS 'Error message';
COMMENT ON COLUMN "rif40_error_messages"."table_name" IS 'Table raising error. If NULL, procedure or other code.';
COMMENT ON COLUMN "rif40_error_messages"."tag" IS 'Contextual tag for error code';
COMMENT ON COLUMN "rif40_geographies"."defaultcomparea" IS 'Default comparison area';
COMMENT ON COLUMN "rif40_geographies"."defaultstudyarea" IS 'Default study area';
COMMENT ON COLUMN "rif40_geographies"."description" IS 'Description';
COMMENT ON COLUMN "rif40_geographies"."geography" IS 'Geography name';
COMMENT ON COLUMN "rif40_geographies"."hierarchytable" IS 'Hierarchy table';
COMMENT ON COLUMN "rif40_geographies"."max_geojson_digits" IS 'Max digits in ST_AsGeoJson() [optimises file size by removing unecessary precision, the default value of 8 is normally fine.]';
COMMENT ON COLUMN "rif40_geographies"."partition" IS 'Enable partitioning. Extract tables will be partition if the number of years >= 2x the RIF40_PARAMETERS parameters Parallelisation [which has a default of 4, so extracts covering 8 years or more will be partitioned]. ';
COMMENT ON COLUMN "rif40_geographies"."postal_point_column" IS 'Column name for postal points (e.g. POSTCODE, ZIP_CODE)';
COMMENT ON COLUMN "rif40_geographies"."postal_population_table" IS 'Postal population table. Table of postal points (e.g. postcodes, ZIP codes); geolevels; X and YCOORDINATES (in projection SRID); male, female and total populations. Converted to SRID points by loader [not in 4326 Web Mercator lat/long]. Used in creating population wieght centroids and in converting postal points to geolevels. Expected columns &lt;postal_point_column&gt;, XCOORDINATE, YCOORDINATE, 1+ &lt;GEOLEVEL_NAME&gt;, MALES, FEMALES, TOTAL';
COMMENT ON COLUMN "rif40_geographies"."srid" IS 'Postgres projection SRID';
COMMENT ON COLUMN "rif40_health_study_themes"."description" IS 'Description';
COMMENT ON COLUMN "rif40_health_study_themes"."theme" IS 'Theme';
COMMENT ON COLUMN "rif40_icd10"."icd10_1char" IS 'ICD10 chapter';
COMMENT ON COLUMN "rif40_icd10"."icd10_3char" IS '3 Character ICD10 code';
COMMENT ON COLUMN "rif40_icd10"."icd10_4char" IS '4 Character ICD10 code';
COMMENT ON COLUMN "rif40_icd10"."text_1char" IS 'ICD10 chapter textual description';
COMMENT ON COLUMN "rif40_icd10"."text_3char" IS '3 Character ICD10 textual description';
COMMENT ON COLUMN "rif40_icd10"."text_4char" IS '4 Character ICD10 textual description';
COMMENT ON COLUMN "rif40_icd9"."icd9_3char" IS '3 Character ICD9 code';
COMMENT ON COLUMN "rif40_icd9"."icd9_4char" IS '4 Character ICD9 code';
COMMENT ON COLUMN "rif40_icd9"."text_3char" IS '3 Character ICD9 textual description';
COMMENT ON COLUMN "rif40_icd9"."text_4char" IS '4 Character ICD9 textual description';
COMMENT ON COLUMN "rif40_icd_o_3"."icd_o_3_1char" IS 'ICD-O-3 chapter';
COMMENT ON COLUMN "rif40_icd_o_3"."icd_o_3_4char" IS '4 Character ICD-O-3 code';
COMMENT ON COLUMN "rif40_icd_o_3"."text_1char" IS 'ICD-O-3 chapter textual description';
COMMENT ON COLUMN "rif40_icd_o_3"."text_4char" IS '4 Character ICD-O-3 textual description';
COMMENT ON COLUMN "rif40_opcs4"."opcs4_1char" IS 'OPCS4 chapter';
COMMENT ON COLUMN "rif40_opcs4"."opcs4_3char" IS '3 Character OPCS4 code';
COMMENT ON COLUMN "rif40_opcs4"."opcs4_4char" IS '4 Character OPCS4 code';
COMMENT ON COLUMN "rif40_opcs4"."text_1char" IS 'OPCS4 chapter textual description';
COMMENT ON COLUMN "rif40_opcs4"."text_3char" IS '3 Character OPCS4 textual description';
COMMENT ON COLUMN "rif40_opcs4"."text_4char" IS '4 Character OPCS4 textual description';
COMMENT ON COLUMN "rif40_outcome_groups"."field_name" IS 'Outcome field name, e.g. ICD_SAHSU_01, ICD_SAHSU';
COMMENT ON COLUMN "rif40_outcome_groups"."multiple_field_count" IS 'Outcome Group multiple field count (0-99). E.g if NULL then field is ICD_SAHSU_01; if 20 then fields are ICD_SAHSU_01 to ICD_SAHSU_20. Field numbers are assumed to tbe left padded to 2 characters with &quot;0&quot; and preceeded by an &quot;_&quot;';
COMMENT ON COLUMN "rif40_outcome_groups"."outcome_group_description" IS 'Outcome Group Description. E.g. &quot;Single variable ICD&quot;';
COMMENT ON COLUMN "rif40_outcome_groups"."outcome_group_name" IS 'Outcome Group Name. E.g SINGLE_VARIABLE_ICD';
COMMENT ON COLUMN "rif40_outcome_groups"."outcome_type" IS 'Outcome type: ICD, ICD-0 or OPCS';
COMMENT ON COLUMN "rif40_outcomes"."current_description_1char" IS 'Field name contianing descriptions for current version 1 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."current_description_2char" IS 'Field name contianing descriptions for current version 2 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."current_description_3char" IS 'Field name contianing descriptions for current version 3 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."current_description_4char" IS 'Field name contianing descriptions for current version 4 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."current_description_5char" IS 'Field name contianing descriptions for current version 5 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."current_lookup_table" IS 'Current lookup table, e.g. RIF40_ICD10. If this is NULL there is no lookup table';
COMMENT ON COLUMN "rif40_outcomes"."current_sub_version" IS 'Current Sub Version, e.g. 11th Revision - 2010';
COMMENT ON COLUMN "rif40_outcomes"."current_value_1char" IS 'Field name containing values for current version 1 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."current_value_2char" IS 'Field name containing values for current version 2 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."current_value_3char" IS 'Field name containing values for current version 3 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."current_value_4char" IS 'Field name containing values for current version 4 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."current_value_5char" IS 'Field name containing values for current version 5 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."current_version" IS 'Current Version, e.g 10 for ICD';
COMMENT ON COLUMN "rif40_outcomes"."outcome_description" IS 'Outcome Description';
COMMENT ON COLUMN "rif40_outcomes"."outcome_type" IS 'Outcome type: ICD, ICD-0 or OPCS';
COMMENT ON COLUMN "rif40_outcomes"."previous_description_1char" IS 'Field name contianing descriptions for previous version 1 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."previous_description_2char" IS 'Field name contianing descriptions for previous version 2 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."previous_description_3char" IS 'Field name contianing descriptions for previous version 3 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."previous_description_4char" IS 'Field name contianing descriptions for previous version 4 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."previous_description_5char" IS 'Field name contianing descriptions for previous version 5 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."previous_lookup_table" IS 'Previous lookup table, e.g. RIF40_ICD9';
COMMENT ON COLUMN "rif40_outcomes"."previous_sub_version" IS 'Previous sub version';
COMMENT ON COLUMN "rif40_outcomes"."previous_value_1char" IS 'Field name containing values for previous version 1 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."previous_value_2char" IS 'Field name containing values for previous version 2 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."previous_value_3char" IS 'Field name containing values for previous version 3 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."previous_value_4char" IS 'Field name containing values for previous version 4 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."previous_value_5char" IS 'Field name containing values for previous version 5 character code (may be NULL)';
COMMENT ON COLUMN "rif40_outcomes"."previous_version" IS 'Previous version, e.g. 9';
COMMENT ON COLUMN "rif40_predefined_groups"."condition" IS 'SQL WHERE clause, with the WHERE keyword omitted). Default to 1=1 (use all records matching year/age/sex criteria). Checked for SQL injection.';
COMMENT ON COLUMN "rif40_predefined_groups"."outcome_type" IS 'Outcome type: ICD, ICD-0 or OPCS';
COMMENT ON COLUMN "rif40_predefined_groups"."predefined_group_description" IS 'Predefined Group Description. E.g. &quot;Lung Cancer&quot;';
COMMENT ON COLUMN "rif40_predefined_groups"."predefined_group_name" IS 'Predefined Group Name. E.g LUNG_CANCER';
COMMENT ON COLUMN "rif40_reference_tables"."table_name" IS 'Table name';
COMMENT ON COLUMN "rif40_study_shares"."grantee_username" IS 'Username granted access by a RIF_MANAGER to study data';
COMMENT ON COLUMN "rif40_study_shares"."grantor" IS 'Username doing grant';
COMMENT ON COLUMN "rif40_study_shares"."study_id" IS 'Unique study index: study_id. Created by SEQUENCE rif40_study_id_seq';
COMMENT ON COLUMN "rif40_table_outcomes"."current_version_start_year" IS 'Year of change from current version to previous version';
COMMENT ON COLUMN "rif40_table_outcomes"."numer_tab" IS 'Numerator table name.';
COMMENT ON COLUMN "rif40_table_outcomes"."outcome_group_name" IS 'Outcome Group Name. E.g SINGLE_VARIABLE_ICD';
COMMENT ON COLUMN "rif40_tables"."age_group_field_name" IS 'Name of AGE_GROUP field. No default. SEX_FIELD_NAME must be set, AGE_SEX_GROUP_FIELD_NAME must not be set.';
COMMENT ON COLUMN "rif40_tables"."age_group_id" IS 'Type of RIF age group in use. Link to RIF40_AGE_GROUP_NAMES. No default.';
COMMENT ON COLUMN "rif40_tables"."age_sex_group_field_name" IS 'Name of AGE_SEX_GROUP field. Default: AGE_SEX_GROUP; AGE_GROUP_FIELD_NAME and SEX_FIELD_NAME must not be set.';
COMMENT ON COLUMN "rif40_tables"."automatic" IS 'Able to be used in automatic RIF40_NUM_DENOM (0/1, default 0). Cannot be applied to direct standardisation denominator. Restricted to 1 denominator per geography to prevent the automatic RIF40_NUM_DENOM having &gt;1 pair per numerator. This restriction is actually enforced in RIF40_NUM_DENOM because of the &quot;ORA-04091: table RIF40.RIF40_TABLES is mutating, trigger/function may not see it&quot; error. A user specific T_RIF40_NUM_DENOM is supplied for other combinations. The default is 0 because of the restrictions.';
COMMENT ON COLUMN "rif40_tables"."description" IS 'Description';
COMMENT ON COLUMN "rif40_tables"."isdirectdenominator" IS 'Is table a denominator to be used in direct standardisation (0/1). E.g. POP_WORLD, POP_EUROPE.';
COMMENT ON COLUMN "rif40_tables"."isindirectdenominator" IS 'Is table a denominator to be used in indirect standardisation (0/1)';
COMMENT ON COLUMN "rif40_tables"."isnumerator" IS 'Is table a numerator  (0/1)';
COMMENT ON COLUMN "rif40_tables"."sex_field_name" IS 'Name of SEX field. No default. AGE_GROUP_FIELD_NAME must be set, AGE_SEX_GROUP_FIELD_NAME must not be set.';
COMMENT ON COLUMN "rif40_tables"."table_name" IS 'RIF table name. Normally the schema owner will not be able to see the health data tables, so no error is raised if the table cannot be resolved to an acceisble object. The schema owner must have access to automatic indirect standardisation denominators.';
COMMENT ON COLUMN "rif40_tables"."theme" IS 'Health Study theme';
COMMENT ON COLUMN "rif40_tables"."total_field" IS 'Total field (when used aggregated tables)';
COMMENT ON COLUMN "rif40_tables"."validation_date" IS 'Date table contents were validated OK.';
COMMENT ON COLUMN "rif40_tables"."year_start" IS 'Year table starts';
COMMENT ON COLUMN "rif40_tables"."year_stop" IS 'Year table stops';
COMMENT ON COLUMN "rif40_version"."cvs_revision" IS 'CVS revison control information for last amendment';
COMMENT ON COLUMN "rif40_version"."schema_amended" IS 'Date schema amended';
COMMENT ON COLUMN "rif40_version"."schema_created" IS 'Date schema created';
COMMENT ON COLUMN "rif40_version"."version" IS 'Version. Used for change control to ensure front end matches database.';
/*
COMMENT ON COLUMN gis.sahsuland_geography.level1 IS 'level1';
COMMENT ON COLUMN gis.sahsuland_geography.level2 IS 'level2';
COMMENT ON COLUMN gis.sahsuland_geography.level3 IS 'level3';
COMMENT ON COLUMN gis.sahsuland_geography.level4 IS 'level4';
COMMENT ON COLUMN gis.sahsuland_level1.level1 IS 'level1';
COMMENT ON COLUMN gis.sahsuland_level1.name IS 'name';
COMMENT ON COLUMN gis.sahsuland_level2.level2 IS 'level2';
COMMENT ON COLUMN gis.sahsuland_level2.name IS 'name';
COMMENT ON COLUMN gis.sahsuland_level3.level3 IS 'level3';
COMMENT ON COLUMN gis.sahsuland_level3.name IS 'name';
COMMENT ON COLUMN gis.sahsuland_level4.level4 IS 'level4';
COMMENT ON COLUMN gis.sahsuland_level4.name IS 'name';
COMMENT ON COLUMN gis.sahsuland_level4.x_coordinate IS 'X Co-ordinate for centroid';
COMMENT ON COLUMN gis.sahsuland_level4.y_coordinate IS 'Y Co-ordinate for centroid';
*/
COMMENT ON COLUMN "t_rif40_comparison_areas"."area_id" IS 'An area id, the value of a geolevel; i.e. the value of the column T_RIF40_GEOLEVELS.GEOLEVEL_NAME in table T_RIF40_GEOLEVELS.LOOKUP_TABLE';
COMMENT ON COLUMN "t_rif40_comparison_areas"."study_id" IS 'Unique study index: study_id. Created by SEQUENCE rif40_study_id_seq';
COMMENT ON COLUMN "t_rif40_comparison_areas"."username" IS 'Username';
COMMENT ON COLUMN "t_rif40_contextual_stats"."area_id" IS 'An area id, the value of a geolevel; i.e. the value of the column T_RIF40_GEOLEVELS.GEOLEVEL_NAME in table T_RIF40_GEOLEVELS.LOOKUP_TABLE';
COMMENT ON COLUMN "t_rif40_contextual_stats"."area_observed" IS 'Total observed in area';
COMMENT ON COLUMN "t_rif40_contextual_stats"."area_population" IS 'Total population in area';
COMMENT ON COLUMN "t_rif40_contextual_stats"."inv_id" IS 'Unique investigation index: inv_id. Created by SEQUENCE rif40_inv_id_seq';
COMMENT ON COLUMN "t_rif40_contextual_stats"."study_id" IS 'Unique study index: study_id. Created by SEQUENCE rif40_study_id_seq';
COMMENT ON COLUMN "t_rif40_contextual_stats"."total_comparision_population" IS 'Total comparison population. Used for internal calculations.';
COMMENT ON COLUMN "t_rif40_contextual_stats"."username" IS 'Username';
COMMENT ON COLUMN "t_rif40_contextual_stats"."variance_high" IS 'Variance (observed &gt; 100). Used for internal calculations.';
COMMENT ON COLUMN "t_rif40_contextual_stats"."variance_low" IS 'Variance (observed &lt;= 100). Used for internal calculations.';
COMMENT ON COLUMN "t_rif40_fdw_tables"."create_status" IS 'Create status: C (Created, no errors), E(Created, errors in test SELECT), N(Not created, errors)';
COMMENT ON COLUMN "t_rif40_fdw_tables"."date_created" IS 'Date FDW table created (or attempted to be)';
COMMENT ON COLUMN "t_rif40_fdw_tables"."error_message" IS 'Error message when create status is: E(Created, errors in test SELECT, N(Not created, errors)';
COMMENT ON COLUMN "t_rif40_fdw_tables"."rowtest_passed" IS 'SELECT rowtest passed (0/1)';
COMMENT ON COLUMN "t_rif40_fdw_tables"."table_name" IS 'RIF table name. Normally the schema owner will not be able to see the health data tables, so no error is raised if the table cannot be resolved to an acceisble object. The schema owner must have access to automatic indirect standardisation denominators.';
COMMENT ON COLUMN "t_rif40_fdw_tables"."username" IS 'User name';
COMMENT ON COLUMN "t_rif40_geolevels"."avg_npoints_geom" IS 'Average number of points in a geometry object (AREA_ID). Used to evaluation the impact of ST_SIMPLIFY_TOLERANCE.';
COMMENT ON COLUMN "t_rif40_geolevels"."avg_npoints_opt" IS 'Average number of points in a ST_SimplifyPreserveTopology() optimsed geometry object (AREA_ID). Used to evaluation the impact of ST_SIMPLIFY_TOLERANCE.';
COMMENT ON COLUMN "t_rif40_geolevels"."centroids_area_id_column" IS 'Column containing the AREA_IDs in CENTROIDS_TABLE. X and Y co-ordinates ciolumns are asummed to be named after CENTROIDXCOORDINATE_COLUMN and CENTROIDYCOORDINATE_COLUMN.';
COMMENT ON COLUMN "t_rif40_geolevels"."centroids_table" IS 'Table containing GIS shape file data with Arc GIS calculated population weighted centroids (created using shp2pgsql). PostGIS does not support population weighted centroids.';
COMMENT ON COLUMN "t_rif40_geolevels"."centroidsfile" IS 'Location of the GIS centroids file. Can also use CENTROIDXCOORDINATE_COLUMN, CENTROIDYCOORDINATE_COLUMN instead.';
COMMENT ON COLUMN "t_rif40_geolevels"."centroidxcoordinate_column" IS 'Lookup table centroid X co-ordinate column name. Can also use CENTROIDSFILE instead.';
COMMENT ON COLUMN "t_rif40_geolevels"."centroidycoordinate_column" IS 'Lookup table centroid Y co-ordinate column name.';
COMMENT ON COLUMN "t_rif40_geolevels"."comparea" IS 'Able to be used as a comparison area (0/1)';
COMMENT ON COLUMN "t_rif40_geolevels"."covariate_table" IS 'Name of table used for covariates at this geolevel';
COMMENT ON COLUMN "t_rif40_geolevels"."description" IS 'Description';
COMMENT ON COLUMN "t_rif40_geolevels"."file_geojson_len" IS 'File length estimate (in bytes) for conversion of the entire geolevel geometry to GeoJSON. Used to evaluation the impact of ST_SIMPLIFY_TOLERANCE.';
COMMENT ON COLUMN "t_rif40_geolevels"."geography" IS 'Geography (e.g EW2001)';
COMMENT ON COLUMN "t_rif40_geolevels"."geolevel_id" IS 'ID for ordering (1=lowest resolution). Up to 99 supported.';
COMMENT ON COLUMN "t_rif40_geolevels"."geolevel_name" IS 'Name of geolevel. This will be a column name in the numerator/denominator tables';
COMMENT ON COLUMN "t_rif40_geolevels"."leg_geom" IS 'The average length (in projection units - usually metres) of a vector leg. Used to evaluation the impact of ST_SIMPLIFY_TOLERANCE.';
COMMENT ON COLUMN "t_rif40_geolevels"."leg_opt" IS 'The average length (in projection units - usually metres) of a ST_SimplifyPreserveTopology() optimsed geometryvector leg. Used to evaluation the impact of ST_SIMPLIFY_TOLERANCE.';
COMMENT ON COLUMN "t_rif40_geolevels"."listing" IS 'Able to be used in a disease map listing (0/1)';
COMMENT ON COLUMN "t_rif40_geolevels"."lookup_desc_column" IS 'Lookup table description column name.';
COMMENT ON COLUMN "t_rif40_geolevels"."lookup_table" IS 'Lookup table name. This is used to translate codes to the common names, e.g a LADUA of 00BK is &quot;Westminster&quot;';
COMMENT ON COLUMN "t_rif40_geolevels"."resolution" IS 'Can use a map for selection at this resolution (0/1)';
COMMENT ON COLUMN "t_rif40_geolevels"."restricted" IS 'Is geolevel access rectricted by Inforamtion Governance restrictions (0/1). If 1 (Yes) then a) students cannot access this geolevel and b) if the system parameter ExtractControl=1 then the user must be granted permission by a RIF_MANAGER to extract from the database the results, data extract and maps tables. This is enforced by the RIF application.';
COMMENT ON COLUMN "t_rif40_geolevels"."shapefile" IS 'Location of the GIS shape file. NULL if PostGress/PostGIS used. Can also use SHAPEFILE_GEOMETRY instead,';
COMMENT ON COLUMN "t_rif40_geolevels"."shapefile_area_id_column" IS 'Column containing the AREA_IDs in SHAPEFILE_TABLE';
COMMENT ON COLUMN "t_rif40_geolevels"."shapefile_desc_column" IS 'Column containing the AREA_ID descriptions in SHAPEFILE_TABLE';
COMMENT ON COLUMN "t_rif40_geolevels"."shapefile_table" IS 'Table containing GIS shape file data (created using shp2pgsql).';
COMMENT ON COLUMN "t_rif40_geolevels"."st_simplify_tolerance" IS 'ST_SimplifyPreserveTopology(geom, st_simplify_tolerance) simplification parameter. Minimum length of a vector in the Douglas-Peucker alogorithm. The actual minimum length (see: ?) is normally 3-4x this parameter. Setting this parameter >20 will result in small slivers as ST_SimplifyPreserveTopology() processes on an object by object basis. Where two objects touch there is no guarantee that vectors in each object will be processed in the same way. Values of up to 1 (the projection unit is usually a metre) massively reduce points with minimal loss in resolution. Values up to 20 result in very small slivers for small objects (e.g. Census output area). Unfortunately the number of points effects the size of the GeoJSON files, so for most geolevels values of 20-500 are needed to create a sanely sized GeoJSON file. The best way to resolve the problem is to reduce to resolution of the input shapefile in ArcGIS to the amount that produces an optimal map at the highest resolution geolevel and simplify from there. It is also possible to sinmplify using the PostGIS Topolgy extension if the shapefile is well formed.';
COMMENT ON COLUMN "t_rif40_inv_conditions"."condition" IS 'SQL WHERE clause, with the WHERE keyword omitted). Default to 1=1 (use all records matching year/age/sex criteria). Checked for SQL injection.';
COMMENT ON COLUMN "t_rif40_inv_conditions"."inv_id" IS 'Unique investigation index: inv_id. Created by SEQUENCE rif40_inv_id_seq';
COMMENT ON COLUMN "t_rif40_inv_conditions"."line_number" IS 'Line number';
COMMENT ON COLUMN "t_rif40_inv_conditions"."study_id" IS 'Unique study index: study_id. Created by SEQUENCE rif40_study_id_seq';
COMMENT ON COLUMN "t_rif40_inv_conditions"."username" IS 'Username';
COMMENT ON COLUMN "t_rif40_inv_covariates"."covariate_name" IS 'Covariate name';
COMMENT ON COLUMN "t_rif40_inv_covariates"."geography" IS 'Geography (e.g EW2001). Cannot be changed by the user; present to allow a foreign key to be enforced.';
COMMENT ON COLUMN "t_rif40_inv_covariates"."inv_id" IS 'Unique investigation index: inv_id. Created by SEQUENCE rif40_inv_id_seq';
COMMENT ON COLUMN "t_rif40_inv_covariates"."max" IS 'Maximum value for a covariate';
COMMENT ON COLUMN "t_rif40_inv_covariates"."min" IS 'Minimum value for a covariate';
COMMENT ON COLUMN "t_rif40_inv_covariates"."study_geolevel_name" IS 'Study area geolevel name. Must be a valid GEOLEVEL_NAME for the study GEOGRPAHY in T_RIF40_GEOLEVELS. Cannot be changed by the user; present to allow a foreign key to be enforced.';
COMMENT ON COLUMN "t_rif40_inv_covariates"."study_id" IS 'Unique study index: study_id. Created by SEQUENCE rif40_study_id_seq';
COMMENT ON COLUMN "t_rif40_inv_covariates"."username" IS 'Username';
COMMENT ON COLUMN "t_rif40_investigations"."classifier" IS 'Maps classifier. EQUAL_INTERVAL: each classifier band represents the same sized range and intervals change based on max an min, JENKS: Jenks natural breaks, QUANTILE: equiheight (even number) distribution, STANDARD_DEVIATION, UNIQUE_INTERVAL: a version of EQUAL_INTERVAL that takes into account unique values, &lt;BESPOKE&gt;; default QUANTILE. &lt;BESPOKE&gt; classification bands are defined in: RIF40_CLASSFIER_BANDS, RIF40_CLASSFIER_BAND_NAMES and are used to create maps that are comparable accross investigations';
COMMENT ON COLUMN "t_rif40_investigations"."classifier_bands" IS 'Map classifier bands; default 5. Must be between 2 and 20';
COMMENT ON COLUMN "t_rif40_investigations"."genders" IS 'Genders to be investigated: 1 - males, 2 female or 3 - both';
COMMENT ON COLUMN "t_rif40_investigations"."geography" IS 'Geography (e.g EW2001)';
COMMENT ON COLUMN "t_rif40_investigations"."inv_description" IS 'Description of investigation';
COMMENT ON COLUMN "t_rif40_investigations"."inv_id" IS 'Unique investigation index: inv_id. Created by SEQUENCE rif40_inv_id_seq';
COMMENT ON COLUMN "t_rif40_investigations"."inv_name" IS 'Name of investigation. Must be a valid database column name, i.e. only contain A-Z0-9_ and start with a letter.';
COMMENT ON COLUMN "t_rif40_investigations"."investigation_state" IS 'Investigation state - C: created, not verfied; V: verified, but no other work done; E - extracted imported or created, but no results or maps created; R: results computed; U: upgraded record from V3.1 RIF (has an indeterminate state; probably R.';
COMMENT ON COLUMN "t_rif40_investigations"."max_age_group" IS 'Maximum age group (LOW_AGE to HIGH_AGE) in RIF40_AGE_GROUPS. OFFSET must be &gt; MIN_AGE_GROUP OFFSET, and a valid AGE_GROUP_ID in RIF40_AGE_GROUP_NAMES.AGE_GROUP_NAME';
COMMENT ON COLUMN "t_rif40_investigations"."mh_test_type" IS 'Mantel-Haenszel test type: &quot;No test&quot;, &quot;Comparison Areas&quot;, &quot;Unexposed Area&quot;.';
COMMENT ON COLUMN "t_rif40_investigations"."min_age_group" IS 'Minimum age group (LOW_AGE to HIGH_AGE) in RIF40_AGE_GROUPS. OFFSET must be &lt; MAX_AGE_GROUP OFFSET, and a valid AGE_GROUP_ID in RIF40_AGE_GROUP_NAMES.AGE_GROUP_NAME';
COMMENT ON COLUMN "t_rif40_investigations"."numer_tab" IS 'Numerator table name. May be &quot;DUMMY&quot; if extract created outside of the RIF.';
COMMENT ON COLUMN "t_rif40_investigations"."study_id" IS 'Unique study index: study_id. Created by SEQUENCE rif40_study_id_seq';
COMMENT ON COLUMN "t_rif40_investigations"."username" IS 'Username';
COMMENT ON COLUMN "t_rif40_investigations"."year_start" IS 'Year investigation is to start. Must be between the limnits specified in the numerator and denominator tables';
COMMENT ON COLUMN "t_rif40_investigations"."year_stop" IS 'Year investigation is to stop';
COMMENT ON COLUMN "t_rif40_num_denom"."denominator_table" IS 'Denominator_ table';
COMMENT ON COLUMN "t_rif40_num_denom"."geography" IS 'Geography (e.g EW2001)';
COMMENT ON COLUMN "t_rif40_num_denom"."numerator_table" IS 'Numerator table';
COMMENT ON COLUMN "t_rif40_parameters"."param_description" IS 'Description';
COMMENT ON COLUMN "t_rif40_parameters"."param_name" IS 'Parameter';
COMMENT ON COLUMN "t_rif40_parameters"."param_value" IS 'Value';
COMMENT ON COLUMN "t_rif40_projects"."date_ended" IS 'Date project ended';
COMMENT ON COLUMN "t_rif40_projects"."date_started" IS 'Date project started';
COMMENT ON COLUMN "t_rif40_projects"."description" IS 'Project description';
COMMENT ON COLUMN "t_rif40_projects"."project" IS 'Project name';
COMMENT ON COLUMN "t_rif40_results"."adjusted" IS 'Covariate adjustment: Unadjusted (0) or adjusted (1)';
COMMENT ON COLUMN "t_rif40_results"."band_id" IS 'A band allocated to the area';
COMMENT ON COLUMN "t_rif40_results"."direct_standardisation" IS 'Standardisation: indirect (0) or direct (1)';
COMMENT ON COLUMN "t_rif40_results"."expected" IS 'The number of expected cases or the rate (for direct standardised results)';
COMMENT ON COLUMN "t_rif40_results"."genders" IS 'Genders to be investigated: 1 - males, 2 female or 3 - both';
COMMENT ON COLUMN "t_rif40_results"."inv_id" IS 'Unique investigation inde:inv_id. Created by SEQUENCE rif40_inv_id_seq';
COMMENT ON COLUMN "t_rif40_results"."lower95" IS 'The lower 95% confidence interval for the relative risk (for indirectly standarised results) or the lower 95% confidence interval for the rate (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."observed" IS 'The number of observed cases';
COMMENT ON COLUMN "t_rif40_results"."posterior_probability" IS 'The posterior probability (for indirectly standarised results) or NULL (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."posterior_probability_lower95" IS 'The lower 95% confidence interval of the posterior probability (for indirectly standarised results) or NULL (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."posterior_probability_upper95" IS 'The upper 95% confidence interval of the posterior probability (for indirectly standarised results) or NULL (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."relative_risk" IS 'Relaitive risk (for indirectly standarised results) or NULL (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."residual_relative_risk" IS 'The residual relative risk(for indirectly standarised results) or NULL (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."residual_rr_lower95" IS 'The lower 95% confidence interval of the residual relative risk(for indirectly standarised results) or NULL (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."residual_rr_upper95" IS 'The upper 95% confidence interval of the residual relative risk(for indirectly standarised results) or NULL (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."smoothed_relative_risk" IS 'Smoothed relaive risk (for indirectly standarised results) or NULL (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."smoothed_smr" IS 'The smoothed SMR [fully Bayesian smoothing] (for indirectly standarised results) or NULL (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."smoothed_smr_lower95" IS 'The lower 95% confidence interval of the smoothed SMR [fully Bayesian smoothing] (for indirectly standarised results) or NULL (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."smoothed_smr_upper95" IS 'The upper 95% confidence interval of the smoothed SMR [fully Bayesian smoothing] (for indirectly standarised results) or NULL (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."study_id" IS 'Unique study index: study_id. Created by SEQUENCE rif40_study_id_seq';
COMMENT ON COLUMN "t_rif40_results"."upper95" IS 'The upper 95% confidence interval for the relative risk (for indirectly standarised results) or the upper 95% confidence interval for the rate (for directly standardised results)';
COMMENT ON COLUMN "t_rif40_results"."username" IS 'Username';
COMMENT ON COLUMN "t_rif40_studies"."audsid" IS 'Link to Oracle audit subsystem. On Postgres is &quot;backend PID.Julian day.Seconds from midnight.uSeconds (backend start time)&quot;. This can be correlated to the logging messages.';
COMMENT ON COLUMN "t_rif40_studies"."authorised_by" IS 'Who authorised extract and/or transfer. Must be a RIF MANAGER.';
COMMENT ON COLUMN "t_rif40_studies"."authorised_notes" IS 'IG authorisation notes. Must be filled in if EXTRACT_PERMITTED=1.';
COMMENT ON COLUMN "t_rif40_studies"."authorised_on" IS 'When was the extract and/or transfer authorised';
COMMENT ON COLUMN "t_rif40_studies"."comparison_geolevel_name" IS 'Comparison area geolevel name. Must be a valid GEOLEVEL_NAME for the study GEOGRPAHY in T_RIF40_GEOLEVELS, with COMPAREA=1';
COMMENT ON COLUMN "t_rif40_studies"."denom_tab" IS 'Denominator table name. May be &quot;DUMMY&quot; if extract created outside of the RIF. Note the old RIF allowed studies to have different denominators between investigations; this capability has been removed to simplify the extract SQL and to allow a single rotated high performance extract table to be used for all investigations in a study. The extract table is then based on the standard rotated denominator (i.e. in age_sex_group, total format rather than M0 .. M5-9 ... etc) with one extract column per covariate and investigation. Multiple investigations may use a different numerator (1 per investigation).';
COMMENT ON COLUMN "t_rif40_studies"."description" IS 'Study description';
COMMENT ON COLUMN "t_rif40_studies"."direct_stand_tab" IS 'Name of table to be used in direct standardisation. COMPARISON_GEOLEVEL_NAME must be NULL. May be &quot;DUMMY&quot; if extract created outside of the RIF. Note the old RIF allowed studies to have different denominators between investigations; this capability has been removed to simplify the extract SQL and to allow a single rotated high performance extract table to be used for all investigations in a study. The extract table is then based on the standard rotated denominator (i.e. in age_sex_group, total format rather than M0 ... M5-9 ... etc) with one extract column per covariate and investigation. Multiple investigations may use a different numerator (1 per investigation).';
COMMENT ON COLUMN "t_rif40_studies"."extract_permitted" IS 'Is extract permitted from the database: 0/1. Only a RIF MANAGER may change this value. This user is still permitted to create and run a RIF study and to view the results. Geolevel access is rectricted by the RIF40_GEOLEVELS.RESTRICTED Inforamtion Governance restrictions (0/1). If 1 (Yes) then a) students cannot access this geolevel and b) if the system parameter ExtractControl=1 then the user must be granted permission by a RIF_MANAGER to extract from the database the results, data extract and maps tables. All students must be granted permission by a RIF_MANAGER for any extract if the system parameter ExtractControl=1. This is enforced by the RIF application.';
COMMENT ON COLUMN "t_rif40_studies"."extract_table" IS 'Extract table. Must only contain A-Z0-9_ and start with a letter.';
COMMENT ON COLUMN "t_rif40_studies"."geography" IS 'Geography (e.g EW2001)';
COMMENT ON COLUMN "t_rif40_studies"."map_table" IS 'Map table. Must only contain A-Z0-9_ and start with a letter.';
COMMENT ON COLUMN "t_rif40_studies"."other_notes" IS 'Study other notes';
COMMENT ON COLUMN "t_rif40_studies"."project" IS 'Project running the study. The user must be allocated to the project.';
COMMENT ON COLUMN "t_rif40_studies"."study_date" IS 'Study date';
COMMENT ON COLUMN "t_rif40_studies"."study_geolevel_name" IS 'Study area geolevel name';
COMMENT ON COLUMN "t_rif40_studies"."study_id" IS 'Unique study index: study_id. Created by SEQUENCE rif40_study_id_seq';
COMMENT ON COLUMN "t_rif40_studies"."study_name" IS 'Study name';
COMMENT ON COLUMN "t_rif40_studies"."study_state" IS 'Study state - C: created, not verfied; V: verified, but no other work done; E - extracted imported or created, but no results or maps created; R: results computed; U: upgraded record from V3.1 RIF (has an indeterminate state; probably R.';
COMMENT ON COLUMN "t_rif40_studies"."study_type" IS 'Study type: 1 - disease mapping, 11 - Risk Analysis (many areas, one band), 12 - Risk Analysis (point sources), 13 - Risk Analysis (exposure covariates), 14 - Risk Analysis (coverage shapefile), 15 - Risk Analysis (exposure shapefile)';
COMMENT ON COLUMN "t_rif40_studies"."summary" IS 'Study summary';
COMMENT ON COLUMN "t_rif40_studies"."suppression_value" IS 'Suppress results with low cell counts below this value. If the role RIF_NO_SUPRESSION is granted and the user is not a RIF_STUDENT then SUPPRESSION_VALUE=0; otherwise is equals the parameter &quot;SuppressionValue&quot;. If >0 all results with the value or below will be set to 0.';
COMMENT ON COLUMN "t_rif40_studies"."transfer_permitted" IS 'Is transfer permitted from the Secure or Private Network: 0/1. This is for purely documentatary purposes only. Only a RIF MANAGER may change this value. The value defaults to the same as EXTRACT_PERMITTED. Only geolevels where RIF40_GEOLEVELS.RESTRICTED=0 may be transferred.';
COMMENT ON COLUMN "t_rif40_studies"."username" IS 'Username';
COMMENT ON COLUMN "t_rif40_study_areas"."area_id" IS 'An area id, the value of a geolevel; i.e. the value of the column T_RIF40_GEOLEVELS.GEOLEVEL_NAME in table T_RIF40_GEOLEVELS.LOOKUP_TABLE';
COMMENT ON COLUMN "t_rif40_study_areas"."band_id" IS 'A band allocated to the area';
COMMENT ON COLUMN "t_rif40_study_areas"."study_id" IS 'Unique study index: study_id. Created by SEQUENCE rif40_study_id_seq';
COMMENT ON COLUMN "t_rif40_study_areas"."username" IS 'Username';
COMMENT ON COLUMN "t_rif40_study_sql"."line_number" IS 'Line number';
COMMENT ON COLUMN "t_rif40_study_sql"."sql_text" IS 'SQL text';
COMMENT ON COLUMN "t_rif40_study_sql"."statement_number" IS 'Statement number';
COMMENT ON COLUMN "t_rif40_study_sql"."statement_type" IS 'Statement type: CREATE, INSERT, POST_INSERT, NUMERATOR_CHECK, DENOMINATOR_CHECK';
COMMENT ON COLUMN "t_rif40_study_sql"."status" IS 'Status: C(reated) or R(un)';
COMMENT ON COLUMN "t_rif40_study_sql"."study_id" IS 'Unique study index: study_id. Created by SEQUENCE rif40_study_id_seq';
COMMENT ON COLUMN "t_rif40_study_sql"."username" IS 'Username';
COMMENT ON COLUMN "t_rif40_study_sql_log"."audsid" IS 'Link to Oracle audit subsystem. On Postgres is &quot;backend PID.Julian day.Seconds from midnight.uSeconds (backend start time)&quot;. This can be correlated to the logging messages.';
COMMENT ON COLUMN "t_rif40_study_sql_log"."elapsed_time" IS 'Elapsed time';
COMMENT ON COLUMN "t_rif40_study_sql_log"."log_message" IS 'Log message';
COMMENT ON COLUMN "t_rif40_study_sql_log"."log_sqlcode" IS 'SQL code (SQLSTATE hex code in Postgres)';
COMMENT ON COLUMN "t_rif40_study_sql_log"."rowcount" IS 'Row count';
COMMENT ON COLUMN "t_rif40_study_sql_log"."start_time" IS 'Start time';
COMMENT ON COLUMN "t_rif40_study_sql_log"."statement_number" IS 'Statement number';
COMMENT ON COLUMN "t_rif40_study_sql_log"."statement_type" IS 'Statement type: CREATE, INSERT, POST_INSERT, NUMERATOR_CHECK, DENOMINATOR_CHECK';
COMMENT ON COLUMN "t_rif40_study_sql_log"."study_id" IS 'Unique study index: study_id. Created by SEQUENCE rif40_study_id_seq';
COMMENT ON COLUMN "t_rif40_study_sql_log"."username" IS 'Username';
COMMENT ON COLUMN "t_rif40_user_projects"."grant_date" IS 'Date project access granted';
COMMENT ON COLUMN "t_rif40_user_projects"."project" IS 'Project name';
COMMENT ON COLUMN "t_rif40_user_projects"."revoke_date" IS 'Date project access revoke_date';
COMMENT ON COLUMN "t_rif40_user_projects"."username" IS 'Username';

COMMENT ON VIEW "rif40_comparison_areas" IS 'Links study areas and bands for a given study.';
COMMENT ON VIEW "rif40_contextual_stats" IS 'Contextual stats for results map. Also includes values used in internal calculations.';
COMMENT ON VIEW "rif40_fdw_tables" IS 'RIF numerator tables which are Foreign data wrappers in Postgres';
COMMENT ON VIEW "rif40_geolevels" IS 'Geolevels: hierarchy of level with a geography. Use this table for SELECT; use T_RIF40_GEOLEVELS for INSERT/UPDATE/DELETE. View with RIF_STUDENT security context support. If the user has the RIF_STUDENT role the geolevels are restricted to e.g. LADUA/DISTRICT level resolution or lower. This is controlled by the RESTRICTED field.';
COMMENT ON VIEW "rif40_inv_conditions" IS 'Lines of SQL conditions pertinent to an investigation.';
COMMENT ON VIEW "rif40_inv_covariates" IS 'Details of each covariate used by an investigation in a study';
COMMENT ON VIEW "rif40_investigations" IS 'Details of each investigation in a study';
COMMENT ON VIEW "rif40_parameters" IS 'RIF40 parameters with automatic SuppressionValue parameter.  Use this table for SELECT; use T_RIF40_PARAMETERS for INSERT/UPDATE/DELETE. User needs RIF_NO_SUPPRESSION granted as a role to see unsuppressed results';
COMMENT ON VIEW "rif40_projects" IS 'RIF projects (restricted to those granted to the user)';
COMMENT ON VIEW "rif40_results" IS 'RIF Results Table';
COMMENT ON VIEW "rif40_studies" IS 'RIF studies';
COMMENT ON VIEW "rif40_study_areas" IS 'Links study areas and bands for a given study.';
COMMENT ON VIEW "rif40_study_sql" IS 'SQL created for study execution.';
COMMENT ON VIEW "rif40_study_sql_log" IS 'Log of SQL executed for study.';
COMMENT ON VIEW "rif40_user_projects" IS 'RIF project users';
COMMENT ON VIEW "rif40_user_version" IS 'User schema revision control view.';

COMMENT ON TABLE "rif40_columns" IS 'RIF40 Columns';
COMMENT ON TABLE "rif40_tables_and_views" IS 'RIF40 Tables and Views';
COMMENT ON TABLE "rif40_triggers" IS 'RIF40 Triggers';
