\echo * Script: ../postgres/create_v4_0_postgres_ddl_control_views.sql autogenerated using: $Id: create_v4_0_postgres_ddl_control_views.sql,v 1.6 2014/03/04 10:53:26 peterh Exp $ by: RIF40 on: 03-MAR-2014
\echo * Create RIF40 Postgres DDL control views (used to check the setup is complete)
-- **************************************************************************
-- *
-- * DO NOT EDIT THIS SCRIPT OR MODIFY THE ORACLE SCHEMA - USE ALTER SCRIPTS
-- *
-- **************************************************************************
/*
-- *************************************************************************************************
--
-- CVS/RCS Header
--
-- $Author: peterh $
-- $Date: 2014/03/04 10:53:26 $
-- Type: Postgres script
-- $RCSfile: create_v4_0_postgres_ddl_control_views.sql,v $
-- $Source: /home/EPH/CVS/repository/SAHSU/projects/rif/V4.0/database/postgres/psql_scripts/create_v4_0_postgres_ddl_control_views.sql,v $
-- $Revision: 1.6 $
-- $Id: create_v4_0_postgres_ddl_control_views.sql,v 1.6 2014/03/04 10:53:26 peterh Exp $
-- $State: Exp $
-- $Locker:  $
--
-- Description:
--
-- Rapid Enquiry Facility (RIF) - Create RIF40 Postgres DDL control views (used to check the setup is complete)
--
-- Copyright:
--
-- The RIF is free software; you can redistribute it and/or modify it under
-- the terms of the GNU General Public License as published by the Free
-- Software Foundation; either version 2, or (at your option) any later
-- version.
--
-- The RIF is distributed in the hope that it will be useful, but WITHOUT ANY
-- WARRANTY; without even the implied warranty of MERCHANTABILITY or
-- FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
-- for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this file; see the file LICENCE.  If not, write to:
--
-- UK Small Area Health Statistics Unit,
-- Dept. of Epidemiology and Biostatistics
-- Imperial College School of Medicine (St. Mary's Campus),
-- Norfolk Place,
-- Paddington,
-- London, W2 1PG
-- United Kingdom
--
-- The RIF uses Oracle 11g, PL/SQL, PostGres and PostGIS as part of its implementation.
--
-- Oracle11g, PL/SQL and Pro*C are trademarks of the Oracle Corporation.
--
-- All terms mentioned in this software and supporting documentation that are known to be trademarks
-- or service marks have been appropriately capitalised. Imperial College cannot attest to the accuracy
-- of this information. The use of a term in this software or supporting documentation should NOT be
-- regarded as affecting the validity of any trademark or service mark.
*/
CREATE TABLE "rif40_columns" (
table_or_view_name_hide varchar(30)
, column_name_hide varchar(30)
, table_or_view_name_href varchar(522)
, column_name_href varchar(847)
, nullable varchar(8)
, oracle_data_type varchar(189)
, comments varchar(4000)
);
GRANT SELECT ON rif40_columns TO rif_user;
CREATE TABLE "rif40_tables_and_views" (
class varchar(13)
, table_or_view varchar(178)
, table_or_view_name_href varchar(413)
, table_or_view_name_hide varchar(30)
, comments varchar(4000)
);
GRANT SELECT ON rif40_tables_and_views TO rif_user;
CREATE TABLE "rif40_triggers" (
table_name varchar(30)
, column_name varchar(4000)
, trigger_name varchar(30)
, trigger_type varchar(16)
, triggering_event varchar(227)
, when_clause varchar(4000)
, action_type varchar(11)
, comments varchar(4000)
);
GRANT SELECT ON rif40_triggers TO rif_user;
