-- Vacuum analyse script auto generated by ../psql_scripts/v4_0_vacuum_analyse.sql
-- ************************************************************************
--
-- GIT Header
--
-- $Format:Git ID: (%h) %ci$
-- $Id$
-- Version hash: $Format:%H$
--
-- Description:
--
-- Rapid Enquiry Facility (RIF) - VACUUM ANALYSE VERBOSE all rif40 owned objects
--
-- Copyright:
--
-- The Rapid Inquiry Facility (RIF) is an automated tool devised by SAHSU
-- that rapidly addresses epidemiological and public health questions using
-- routinely collected health and population data and generates standardised
-- rates and relative risks for any given health outcome, for specified age
-- and year ranges, for any given geographical area.
--
-- Copyright 2014 Imperial College London, developed by the Small Area
-- Health Statistics Unit. The work of the Small Area Health Statistics Unit
-- is funded by the Public Health England as part of the MRC-PHE Centre for
-- Environment and Health. Funding for this project has also been received
-- from the Centers for Disease Control and Prevention.
--
-- This file is part of the Rapid Inquiry Facility (RIF) project.
-- RIF is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Lesser General Public License as published by
-- the Free Software Foundation, either verquote_ident(l_schema)||.||quote_ident(l_tablesion 3 of the License, or
-- (at your option) any later version.
--
-- RIF is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU Lesser General Public License for more details.
--
-- You should have received a copy of the GNU Lesser General Public License
-- along with RIF. If not, see <http://www.gnu.org/licenses/>; or write
-- to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
-- Boston, MA 02110-1301 USA
--
-- Author:
--
-- Peter Hambly, SAHSU
--
 VACUUM ANALYZE VERBOSE g_rif40_comparison_areas;
 VACUUM ANALYZE VERBOSE g_rif40_study_areas;
 VACUUM ANALYZE VERBOSE rif40_a_and_e;
 VACUUM ANALYZE VERBOSE rif40_age_group_names;
 VACUUM ANALYZE VERBOSE rif40_age_groups;
 VACUUM ANALYZE VERBOSE rif40_columns;
 VACUUM ANALYZE VERBOSE rif40_covariates;
 VACUUM ANALYZE VERBOSE rif40_dual;
 VACUUM ANALYZE VERBOSE rif40_error_messages;
 VACUUM ANALYZE VERBOSE rif40_geographies;
 VACUUM ANALYZE VERBOSE rif40_health_study_themes;
 VACUUM ANALYZE VERBOSE rif40_icd_o_3;
 VACUUM ANALYZE VERBOSE rif40_icd10;
 VACUUM ANALYZE VERBOSE rif40_icd9;
 VACUUM ANALYZE VERBOSE rif40_opcs4;
 VACUUM ANALYZE VERBOSE rif40_outcome_groups;
 VACUUM ANALYZE VERBOSE rif40_outcomes;
 VACUUM ANALYZE VERBOSE rif40_population_europe;
 VACUUM ANALYZE VERBOSE rif40_population_us;
 VACUUM ANALYZE VERBOSE rif40_population_world;
 VACUUM ANALYZE VERBOSE rif40_predefined_groups;
 VACUUM ANALYZE VERBOSE rif40_reference_tables;
 VACUUM ANALYZE VERBOSE rif40_study_shares;
 VACUUM ANALYZE VERBOSE rif40_table_outcomes;
 VACUUM ANALYZE VERBOSE rif40_tables;
 VACUUM ANALYZE VERBOSE rif40_tables_and_views;
 VACUUM ANALYZE VERBOSE rif40_triggers;
 VACUUM ANALYZE VERBOSE rif40_version;
 VACUUM ANALYZE VERBOSE sahsuland_cancer;
 VACUUM ANALYZE VERBOSE sahsuland_covariates_level3;
 VACUUM ANALYZE VERBOSE sahsuland_covariates_level4;
 VACUUM ANALYZE VERBOSE sahsuland_geography;
 VACUUM ANALYZE VERBOSE sahsuland_level1;
 VACUUM ANALYZE VERBOSE sahsuland_level2;
 VACUUM ANALYZE VERBOSE sahsuland_level3;
 VACUUM ANALYZE VERBOSE sahsuland_level4;
 VACUUM ANALYZE VERBOSE sahsuland_pop;
 VACUUM ANALYZE VERBOSE t_rif40_comparison_areas;
 VACUUM ANALYZE VERBOSE t_rif40_contextual_stats;
 VACUUM ANALYZE VERBOSE t_rif40_fdw_tables;
 VACUUM ANALYZE VERBOSE t_rif40_geolevels;
 VACUUM ANALYZE VERBOSE t_rif40_geolevels_geometry_sahsu_level1;
 VACUUM ANALYZE VERBOSE t_rif40_geolevels_geometry_sahsu_level2;
 VACUUM ANALYZE VERBOSE t_rif40_geolevels_geometry_sahsu_level3;
 VACUUM ANALYZE VERBOSE t_rif40_geolevels_geometry_sahsu_level4;
 VACUUM ANALYZE VERBOSE t_rif40_inv_conditions;
 VACUUM ANALYZE VERBOSE t_rif40_inv_covariates;
 VACUUM ANALYZE VERBOSE t_rif40_investigations;
 VACUUM ANALYZE VERBOSE t_rif40_num_denom;
 VACUUM ANALYZE VERBOSE t_rif40_parameters;
 VACUUM ANALYZE VERBOSE t_rif40_projects;
 VACUUM ANALYZE VERBOSE t_rif40_results;
 VACUUM ANALYZE VERBOSE t_rif40_sahsu_geometry;
 VACUUM ANALYZE VERBOSE t_rif40_studies;
 VACUUM ANALYZE VERBOSE t_rif40_study_areas;
 VACUUM ANALYZE VERBOSE t_rif40_study_sql;
 VACUUM ANALYZE VERBOSE t_rif40_study_sql_log;
 VACUUM ANALYZE VERBOSE t_rif40_user_projects;
 VACUUM ANALYZE VERBOSE x_ew01_cntry2001;
 VACUUM ANALYZE VERBOSE x_ew01_coa2001;
 VACUUM ANALYZE VERBOSE x_ew01_gor2001;
 VACUUM ANALYZE VERBOSE x_ew01_ladua2001;
 VACUUM ANALYZE VERBOSE x_ew01_scntry2001;
 VACUUM ANALYZE VERBOSE x_ew01_soa2001;
 VACUUM ANALYZE VERBOSE x_ew01_ward2001;
 VACUUM ANALYZE VERBOSE x_ew01_ward2001_centroids;
 VACUUM ANALYZE VERBOSE x_sahsu_cen_level4;
 VACUUM ANALYZE VERBOSE x_sahsu_level1;
 VACUUM ANALYZE VERBOSE x_sahsu_level2;
 VACUUM ANALYZE VERBOSE x_sahsu_level3;
 VACUUM ANALYZE VERBOSE x_sahsu_level4;
 VACUUM ANALYZE VERBOSE x_uk91_cen_ed91;
 VACUUM ANALYZE VERBOSE x_uk91_country91;
 VACUUM ANALYZE VERBOSE x_uk91_county91;
 VACUUM ANALYZE VERBOSE x_uk91_district91;
 VACUUM ANALYZE VERBOSE x_uk91_ed91;
 VACUUM ANALYZE VERBOSE x_uk91_region91;
 VACUUM ANALYZE VERBOSE x_uk91_scountry91;
 VACUUM ANALYZE VERBOSE x_uk91_ward91;

--
-- Eof
