
/*

THIS SCRIPT IS NO LONGER AUTOGENERATED 

-- *************************************************************************************************
--
-- CVS/RCS Header
--
-- $Author: peterh $
-- $Date: 2014/02/28 10:54:04 $
-- Type: Postgres script
-- $RCSfile: v4_0_postgres_sahsuland_imports.sql,v $
-- $Source: /home/EPH/CVS/repository/SAHSU/projects/rif/V4.0/database/postgres/sahsuland/v4_0_postgres_sahsuland_imports.sql,v $
-- $Revision: 1.5 $
-- $Id: v4_0_postgres_sahsuland_imports.sql,v 1.5 2014/02/28 10:54:04 peterh Exp $
-- $State: Exp $
-- $Locker:  $
--
-- Description:
--
-- Rapid Enquiry Facility (RIF) - Script to import SAHSULAND data from ../sahsuland/data/ in dependency order
--
-- Copyright:
--
-- The RIF is free software; you can redistribute it and/or modify it under
-- the terms of the GNU General Public License as published by the Free
-- Software Foundation; either version 2, or (at your option) any later
-- version.
--
-- The RIF is distributed in the hope that it will be useful, but WITHOUT ANY
-- WARRANTY; without even the implied warranty of MERCHANTABILITY or
-- FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
-- for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this file; see the file LICENCE.  If not, write to:
--
-- UK Small Area Health Statistics Unit,
-- Dept. of Epidemiology and Biostatistics
-- Imperial College School of Medicine (St. Mary's Campus),
-- Norfolk Place,
-- Paddington,
-- London, W2 1PG
-- United Kingdom
--
-- The RIF uses Oracle 11g, PL/SQL, PostGres and PostGIS as part of its implementation.
--
-- Oracle11g, PL/SQL and Pro*C are trademarks of the Oracle Corporation.
--
-- All terms mentioned in this software and supporting documentation that are known to be trademarks
-- or service marks have been appropriately capitalised. Imperial College cannot attest to the accuracy
-- of this information. The use of a term in this software or supporting documentation should NOT be
-- regarded as affecting the validity of any trademark or service mark.
*/

\COPY t_rif40_num_denom FROM '../sahsuland/data/t_rif40_num_denom.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_dual FROM '../sahsuland/data/rif40_dual.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY t_rif40_projects FROM '../sahsuland/data/t_rif40_projects.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_version FROM '../sahsuland/data/rif40_version.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_error_messages FROM '../sahsuland/data/rif40_error_messages.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_outcomes FROM '../sahsuland/data/rif40_outcomes.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_icd9 FROM '../sahsuland/data/rif40_icd9.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_icd10 FROM '../sahsuland/data/rif40_icd10.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_opcs4 FROM '../sahsuland/data/rif40_opcs4.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_icd_o_3 FROM '../sahsuland/data/rif40_icd_o_3.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_a_and_e FROM '../sahsuland/data/rif40_a_and_e.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_population_world FROM '../sahsuland/data/rif40_population_world.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_population_europe FROM '../sahsuland/data/rif40_population_europe.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_population_us FROM '../sahsuland/data/rif40_population_us.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_reference_tables FROM '../sahsuland/data/rif40_reference_tables.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY sahsuland_pop FROM '../sahsuland/data/sahsuland_pop.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY sahsuland_cancer FROM '../sahsuland/data/sahsuland_cancer.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY sahsuland_geography FROM '../sahsuland/data/sahsuland_geography.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY sahsuland_covariates_level3 FROM '../sahsuland/data/sahsuland_covariates_level3.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY sahsuland_covariates_level4 FROM '../sahsuland/data/sahsuland_covariates_level4.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_age_group_names FROM '../sahsuland/data/rif40_age_group_names.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_outcome_groups FROM '../sahsuland/data/rif40_outcome_groups.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_predefined_groups FROM '../sahsuland/data/rif40_predefined_groups.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_age_groups FROM '../sahsuland/data/rif40_age_groups.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY t_rif40_fdw_tables FROM '../sahsuland/data/t_rif40_fdw_tables.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');

\COPY rif40_columns FROM '../sahsuland/data/rif40_columns.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_tables_and_views FROM '../sahsuland/data/rif40_tables_and_views.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');
\COPY rif40_triggers FROM '../sahsuland/data/rif40_triggers.csv' WITH (FORMAT csv, QUOTE '"', ESCAPE '\');

--
-- Eof
