/**
 *
 * <hr>
 * The Rapid Inquiry Facility (RIF) is an automated tool devised by SAHSU 
 * that rapidly addresses epidemiological and public health questions using 
 * routinely collected health and population data and generates standardised 
 * rates and relative risks for any given health outcome, for specified age 
 * and year ranges, for any given geographical area.
 *
 * Copyright 2017 Imperial College London, developed by the Small Area
 * Health Statistics Unit. The work of the Small Area Health Statistics Unit 
 * is funded by the Public Health England as part of the MRC-PHE Centre for 
 * Environment and Health. Funding for this project has also been received 
 * from the United States Centers for Disease Control and Prevention.  
 *
 * <pre> 
 * This file is part of the Rapid Inquiry Facility (RIF) project.
 * RIF is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * RIF is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with RIF. If not, see <http://www.gnu.org/licenses/>; or write 
 * to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, 
 * Boston, MA 02110-1301 USA
 * </pre>
 *
 * <hr>
 * Peter Hambly
 * @author phambly
 *
 * SQL statement name: 	denominatorReport.sql
 * Type:				Microsoft SQL Server SQL
 * Parameters (preceded by %):
 *						1: Extract table name; e.g. s367_extract
 *
 * Description:			Denominator SQL report. Handles gendes: males, females or both
 * Note:				NO SUPPORT FOR ESCAPING!
 *						Requires rif40.generate_series() to be created to have the same functionality
 *						as Postgres version
 *
 * DO NOT EDIT THIS FILE UNLESS YOU WANT TO CHANGE THE HTML REPORT. 
 * COPY THE ORIGINAL TO %CATALINA_HOME%\conf\dataStorageLayerSQL\<dir> directory OR IT WILL BE 
 * OVERWRITTEN BY UPGRADES.
 *
 * <dir> is "ms", "pg" or "common" in the resources directory:
 * %CATALINA_HOME%\webapps\rifServices\WEB-INF\classes\dataStorageLayerSQL
 */
WITH a AS (
	SELECT c.year, 
	       c.sex,
		   SUM(c.total_pop) AS c_total_pop,
		   SUM(s.total_pop) AS s_total_pop
	  FROM %1 c
				FULL OUTER JOIN %1 s ON (
					c.sex = s.sex AND c.year = s.year AND s.study_or_comparison = 'S')
	 WHERE c.study_or_comparison = 'C'   
	 GROUP BY c.year, c.sex
) 
SELECT a.year, 
       a.c_total_pop comparison_males, 
       b.c_total_pop comparison_females, 
	   a.c_total_pop + b.c_total_pop AS comparison_both,
	   a.s_total_pop AS study_males, 
	   b.s_total_pop AS study_females,
	   a.s_total_pop + b.s_total_pop AS study_both
  FROM a a
			FULL OUTER JOIN a b ON (
				a.year = b.year AND b.sex = 2 /* Females */) 
 WHERE a.sex = 1 /* Males */
 ORDER BY year;
 