--
-- ************************************************************************
--
-- Description:
--
-- Rapid Enquiry Facility (RIF) - Database creation autogenerated temp script to create tablespace and databases
--
DROP DATABASE IF EXISTS sahsuland;
CREATE DATABASE sahsuland WITH OWNER rif40 /* No sahsuland tablespace */;
COMMENT ON DATABASE sahsuland IS 'RIF V4.0 PostGres sahsuland Example Database';
--
-- Eof
