--
-- ************************************************************************
--
-- Description:
--
-- Rapid Enquiry Facility (RIF) - Database creation autogenerated temp script to create tablespace and databases
--
DROP DATABASE IF EXISTS trumpton;
CREATE DATABASE trumpton WITH OWNER rif40 /* No trumpton tablespace */;
COMMENT ON DATABASE trumpton IS 'RIF V4.0 PostGres trumpton Example Database';
--
-- Eof
